### ISSUE TITLE
Remote binding issue

### ISSUE THREAD

**Issue by alpharou** [dmillerw/RemoteIO#45]
When I try to bind a block far away from the remote interface it keep flashing in orange and I can't do anything at all. Version 1.4.2

**Comment by dmillerw** [comment]
Is the other block chunk-loaded

**Comment by alpharou** [comment]
It's an ender quarry from extra utilities. It chunkloads itself but i'm using an external chunkloader too.

**Comment by alpharou** [comment]
This happens in 1.4.1 and 1.4.2, and if you quit and save and try to enter again the game crashes and (this is my problem) i can't get the crash because java is running bad im my computer and the laucher gets messy.

**Comment by dmillerw** [comment]
Well, I need a crash log, otherwise I can't do much of anything

**Comment by shadowsyllvet** [comment]
Having a similar issue,(I think..)
Attempted to link a remote interface cross dimension using railcraft chunk loader. I can confirm the chunk loader is working due to filling a furnace and crossing over to the nether. The interface will link if the target is inside of a "nearby" chunk(within visual range), normally I'd say my chunk loader was broken but everything else still works while I'm cross dimension. Going to update forge and see if it fixes the problem.
