### ISSUE TITLE
[0.0.3] Strange bed behavior

### ISSUE THREAD

**Issue by SPMoo66** [dmillerw/RemoteIO#86]
I'm probably going to have difficulty explaining this, so I'll start with a video.

https://u.pomf.is/umxbqu.mp4

First of all, beds are only rendered as either the top or bottom half, similar issue with doors. This is just a tiny visual bug so it isn't the real problem.

Another is how beds appear as normal, then turn back into the block analyzer visually after you die or unload/reload the chunk.

Also, if you use a bed during the night, it will teleport you to the block analyzer.

**Comment by dmillerw** [comment]
I'm tentatively saying won't-fix on this one, but I've split the interface losing its render into a separate issue ( #96 )

As for the weird bed render issue, it's because the bed is technically two blocks, so the Remote Interface only ever renders what's directly connected to it

As for the spawning, the bed block itself processes the setting of the spawn point, and the bed block is only aware of its own position
